### ISSUE TITLE
Polish Data Page / unit_page_view.dart

### ISSUE THREAD

**Issue by mikkwin** [mikkwin/Bachelor#71]
### Description
unit_page_view.dart skal have en ordenlig UI, som passer til resten af app'en.
Derudover skal den også vise generelle informationer om køretøj og ejer (Hvis det kan findes.)
### Tasks
- [x] Lav widget til generel information.
- [x] Lav widget til knapper
- [x] Kombiner det hele
### UI Elements
Billede af UI element kan findes på mikkels computer. **Før denne task kan godkendes skal billedet være uploadet**.
#### Usability test
- [ ] Nemt at navigere
- [ ] Nemt at bruge
- [ ] Overskuelige knapper og information
