### ISSUE TITLE
Create data stoaring object on unit page

### ISSUE THREAD

**Issue by toften05** [mikkwin/Bachelor#78]
### Description
Implement on unit page view, that it gets the device data and creates an object with all the data, so that when it opens settings it can give the needed data from the object to those pages, so the pages dont have to make a call to the backend. 
### Tasks
Include all the tasks that needs to be made to consider the job done.
- [ ] Get the data fron the backend
- [ ] Create an object that has all the needed data
- [ ] send the needed object data to settings
### Tests
The frontend must be either tested on usability or on logic. Before an issue can be considered done it must have passed either test. **This section cannot be omitted**
- [ ] blackbox testing, when settings page is opened, the data should show. -can only be done after the settings page has been updated.
